minimumReleaseAge: 0

catalog:
    vite: npm:@voidzero-dev/vite-plus-core@0.3.0
    vite-plus: 0.3.0
    vitest: 4.1.11
    oxfmt: 0.64.0
    oxlint: 1.79.0

overrides:
    vite@*: 'catalog:'
    vitest@*: 'catalog:'
    oxfmt: 'catalog:'
    oxlint: 'catalog:'

peerDependencyRules:
    allowAny:
        - vite
    allowedVersions:
        vite: '*'

allowBuilds:
    esbuild: false
    lmdb: false
    msgpackr-extract: false
