/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout/route'
import { Route as LayoutPageImport } from './routes/_layout/page'

// Create/Update Routes

const LayoutRouteRoute = LayoutRouteImport.update({
	id: '/_layout',
	getParentRoute: () => rootRoute,
} as any)

const LayoutPageRoute = LayoutPageImport.update({
	path: '/',
	getParentRoute: () => LayoutRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
	interface FileRoutesByPath {
		'/_layout': {
			id: '/_layout'
			path: ''
			fullPath: ''
			preLoaderRoute: typeof LayoutRouteImport
			parentRoute: typeof rootRoute
		}
		'/_layout/': {
			id: '/_layout/'
			path: '/'
			fullPath: '/'
			preLoaderRoute: typeof LayoutPageImport
			parentRoute: typeof LayoutRouteImport
		}
	}
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
	LayoutRouteRoute: LayoutRouteRoute.addChildren({ LayoutPageRoute }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_layout"
      ]
    },
    "/_layout": {
      "filePath": "_layout/route.tsx",
      "children": [
        "/_layout/"
      ]
    },
    "/_layout/": {
      "filePath": "_layout/page.tsx",
      "parent": "/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
